// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvagsgtlmfkdpnklvdro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2YWdzZ3RsbWZrZHBua2x2ZHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDAzNjAsImV4cCI6MjA3MTU3NjM2MH0.Hs4HFJMqEyA-j4CWfmW9mfwEDf7wxqEuhW99xrt-jxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});